FROM node:alpine as build

WORKDIR /app

COPY package*.json .

RUN yarn

COPY . .

RUN yarn run build

FROM nginx:stable-alpine

WORKDIR /usr/share/nginx/html

RUN rm -rf ./*

COPY nginx.conf /etc/nginx/nginx.conf

COPY --from=build /app/build .

EXPOSE 80 443