version: '3'
services:
  server:
    image: server:latest
    build:
      context: ./server/
      dockerfile: Dockerfile.server
    container_name: server
    ports:
      - 8080:8080
  
  client:
    image: client:latest
    build: 
      context: ./client/
      dockerfile: Dockerfile.client
    container_name: client
    ports:
      - 4200:80
    links:
      - server